apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-pgvector
  namespace: skala-practice
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-db
        image: postgres:15-alpine
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgres.skala-practice.svc.cluster.local -U postgres; do
            sleep 2
          done
          
          echo "Creating pgvector extension..."
          PGPASSWORD="${POSTGRES_PASSWORD}" psql -h postgres.skala-practice.svc.cluster.local -U postgres -d ahub_vectordb -c "CREATE EXTENSION IF NOT EXISTS vector;"
          
          echo "Verifying pgvector extension..."
          PGPASSWORD="${POSTGRES_PASSWORD}" psql -h postgres.skala-practice.svc.cluster.local -U postgres -d ahub_vectordb -c "\dx"
          
          echo "Database initialization complete!"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password