# =========================
# 1. Postgres Secret
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: skala-practice
type: Opaque
stringData:
  postgres-password: wldms0615!