apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk066-backend
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk066-backend
  template:
    metadata:
      labels:
        app: sk066-backend
    spec:
      # ✅ Docker Hub는 public이면 imagePullSecrets 불필요
      # imagePullSecrets:
      #   - name: skala-registry-secret
      
      containers:
        - name: backend
          image: your-dockerhub-username/sk066-backend:latest  # ← 변경 필요
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.skala-practice.svc.cluster.local:5432/ahub_vectordb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
                  optional: true
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
                  optional: true
          
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: sk066-backend
  namespace: skala-practice
spec:
  type: ClusterIP
  selector:
    app: sk066-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http