apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk066-backend
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk066-backend
  template:
    metadata:
      labels:
        app: sk066-backend
    spec:
      # ✅ 프라이빗 레지스트리 로그인용 Secret
      imagePullSecrets:
        - name: skala-registry-secret
      
      containers:
        - name: backend
          image: amdp-registry.skala-ai.com/skala25a/sk066-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.skala-practice.svc.cluster.local:5432/ahub_vectordb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
                  optional: true
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
                  optional: true
          
          resources:
            requests:
              memory: "128Mi"  # ✅ 최소 요구사항으로 감소
              cpu: "50m"       # ✅ 최소 요구사항으로 감소
            limits:
              memory: "512Mi"
              cpu: "500m"
          
          # ⚠️ 헬스체크 임시 비활성화
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 120
          #   periodSeconds: 10
          #   failureThreshold: 5
          #   timeoutSeconds: 5
          
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 90
          #   periodSeconds: 10
          #   failureThreshold: 5
          #   timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sk066-backend
  namespace: skala-practice
spec:
  type: ClusterIP
  selector:
    app: sk066-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http