apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sk066-myfirst-api-server
  namespace: skala-argocd
spec:
  destination:
    namespace: skala-practice
    server: https://96BD83E8CE5CE0396D006BC5CEB350B0.gr7.ap-northeast-2.eks.amazonaws.com
  project: skala
  source:
    path: k8s
    repoURL: https://github.com/kimjieunchol/myfirst-api-server.git
    targetRevision: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=background
